language: rust
rust:
  - nightly
script:
  - mkdir -p gcc-symlinks
  - ln -s /usr/bin/g++-6 gcc-symlinks/g++
  - ln -s /usr/bin/gcc-6 gcc-symlinks/gcc
  - ln -s /usr/bin/gcov-6 gcc-symlinks/gcov
  - export PATH=$PWD/gcc-symlinks:$PATH
  - cargo build --verbose
  - cargo test -- --nocapture
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
