sudo: required
language: rust
rust:
  - nightly
script:
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-$COMPILER_VER g++-$COMPILER_VER
  - mkdir -p gcc-symlinks
  - ln -s /usr/bin/g++-$COMPILER_VER gcc-symlinks/g++
  - ln -s /usr/bin/gcc-$COMPILER_VER gcc-symlinks/gcc
  - ln -s /usr/bin/gcov-$COMPILER_VER gcc-symlinks/gcov
  - export PATH=$PWD/gcc-symlinks:$PATH
  - cargo build --verbose
  - cargo test -- --nocapture
env:
  - COMPILER_VER=4.9
  - COMPILER_VER=5
  - COMPILER_VER=6
