sudo: false
language: rust
matrix:
  include:
    - os: linux
      rust: stable
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - llvm-4.0
            - gcc-4.9
            - g++-4.9
      env:
        - COMPILER_VER=4.9

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - llvm-4.0
            - gcc-4.9
            - g++-4.9
      env:
        - COMPILER_VER=4.9

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - llvm-4.0
            - gcc-5
            - g++-5
      env:
        - COMPILER_VER=5

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - llvm-4.0
            - gcc-6
            - g++-6
      env:
        - COMPILER_VER=6

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - llvm-4.0
            - gcc-7
            - g++-7
      env:
        - COMPILER_VER=7
install:
    - mkdir -p symlinks
    - ln -s /usr/bin/clang-4.0 symlinks/clang
    - ln -s /usr/bin/clang++-4.0 symlinks/clang++
    - ln -s /usr/bin/llvm-cov-4.0 symlinks/llvm-cov
    - ln -s /usr/bin/llvm-config-4.0 symlinks/llvm-config
    - ln -s /usr/bin/gcc-${COMPILER_VER} symlinks/gcc
    - ln -s /usr/bin/g++-${COMPILER_VER} symlinks/g++
    - ln -s /usr/bin/gcov-${COMPILER_VER} symlinks/gcov
script:
    - export PATH=$PWD/symlinks:$PATH
    - gcc --version
    - clang --version
    - cargo build --verbose
    - cargo test -- --nocapture
