[package]
name = "grcov"
version = "0.1.20"
authors = ["Marco Castelluccio <mcastelluccio@mozilla.com>"]

[dependencies]
crossbeam = "0.2"
serde_json = "0.9"
walkdir = "1"
num_cpus = "1.2.1"
semver = "0.6"
rust-crypto = "^0.2"
zip = { version = "0.2.2", default-features = false }
tempdir = "0.3.5"
uuid = { version = "0.4", features = ["v4"] }
libc = "0.2.22"

[features]
# For the system allocator feature.
alloc_system = []
